#!/usr/bin/env bash
# Fake pct: logs calls; fails on the subcommand named in $STUB_PCT_FAIL.
printf 'pct %s\n' "$*" >>"$STUB_LOG"
[[ ${STUB_PCT_FAIL:-} == "$1" ]] && exit 1
[[ -n ${STUB_PCT_FAIL_MATCH:-} && "$*" == *"$STUB_PCT_FAIL_MATCH"* ]] && exit 1
[[ $1 == push && -n ${STUB_PUSH_DIR:-} ]] && cp "$3" "$STUB_PUSH_DIR/$(basename "$4")"
exit 0
